// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Barnacle_Bill = 0,
	Pirate_on_Beach = 1,
	Singer = 2,
	Surfer = 3,
	Shopkeeper = 4,
	Random_person_in_bar_1 = 5,
	Skyler = 6,
	Random_person_in_bar_2 = 7,
	Random_person_in_bar_3 = 8,
	Town_elder = 9,
}
